# Generated by Django 2.2.2 on 2019-06-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('Name', models.CharField(max_length=36, primary_key='True', serialize=False)),
                ('Pnum', models.CharField(max_length=36, null='Flase')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.CharField(max_length=36, primary_key='True', serialize=False)),
                ('Password', models.CharField(max_length=20, null='Flase')),
                ('Plan', models.CharField(max_length=20, null='Flase')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('Name', models.CharField(max_length=36, primary_key='True', serialize=False)),
                ('Author', models.CharField(max_length=20)),
                ('Econtent', models.CharField(max_length=6000, null='Flase')),
                ('Ccontent', models.CharField(max_length=6000, null='Flase')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Album')),
            ],
        ),
    ]
