# Generated by Django 2.2.2 on 2019-06-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.User')),
                ('Pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Passage')),
            ],
        ),
    ]
