# Generated by Django 2.2.2 on 2019-06-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='Pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Album'),
        ),
    ]
