# Generated by Django 2.2.2 on 2019-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20190627_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Img',
            field=models.CharField(max_length=36, null='Flase'),
            preserve_default='Flase',
        ),
    ]
